set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD LVCMOS33} [get_ports {wr_data[0]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD LVCMOS33} [get_ports {wr_data[1]}]
set_property -dict {PACKAGE_PIN N1 IOSTANDARD LVCMOS33} [get_ports {wr_data[2]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {wr_data[3]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {wr_data[4]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD LVCMOS33} [get_ports {wr_data[5]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {wr_data[6]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports {wr_data[7]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports wr_en]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD LVCMOS33} [get_ports rd_en]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports full]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports empty]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports {d_en[0]}]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports {d_en[1]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {d_en[2]}]
set_property -dict {PACKAGE_PIN E4 IOSTANDARD LVCMOS33} [get_ports {d_en[3]}]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports {d_seg[0]}]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports {d_seg[1]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD LVCMOS33} [get_ports {d_seg[2]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports {d_seg[3]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports {d_seg[4]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {d_seg[5]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD LVCMOS33} [get_ports {d_seg[6]}]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports {d_seg[7]}]

#create_clock -period 10.000 -name clock -waveform {0.000 5.000} -add [get_ports clk]
#set _xlnx_shared_i0 [get_pins -hierarchical *]
#set_clock_uncertainty 1.000 $_xlnx_shared_i0
#set_system_jitter 1.000
#set_input_delay -clock [get_clocks clock] -add_delay 1.000 [get_ports {rd_en reset {wr_data[0]} {wr_data[1]} {wr_data[2]} {wr_data[3]} {wr_data[4]} {wr_data[5]} {wr_data[6]} {wr_data[7]} wr_en}]
#set_output_delay -clock [get_clocks clock] -add_delay 1.000 [get_ports -filter { NAME =~  "*" && DIRECTION == "OUT" }]
